const fs = require("fs");
const {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  ImageRun, AlignmentType, HeadingLevel, BorderStyle, WidthType, ShadingType,
  LevelFormat, PageNumber, Footer
} = require("docx");

const CW = 9360; // content width DXA (US Letter, 1" margins)

// ---------- helpers ----------
const P = (text, opts = {}) => new Paragraph({
  alignment: opts.align || AlignmentType.JUSTIFIED,
  spacing: { after: opts.after ?? 140, line: 276 },
  children: [new TextRun({ text, bold: opts.bold, italics: opts.italics, size: opts.size || 22 })],
});
const H1 = (t) => new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun(t)] });
const H2 = (t) => new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun(t)] });
const bullet = (t) => new Paragraph({ numbering: { reference: "b", level: 0 },
  spacing: { after: 80 }, children: [new TextRun({ text: t, size: 22 })] });

function fig(file, caption, wPx, hPx) {
  const items = [];
  items.push(new Paragraph({
    alignment: AlignmentType.CENTER, spacing: { before: 120, after: 40 },
    children: [new ImageRun({ type: "png", data: fs.readFileSync(file),
      transformation: { width: wPx, height: hPx },
      altText: { title: caption, description: caption, name: file } })],
  }));
  items.push(new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 180 },
    children: [new TextRun({ text: caption, italics: true, size: 19 })] }));
  return items;
}

const bd = { style: BorderStyle.SINGLE, size: 1, color: "AAAAAA" };
const borders = { top: bd, bottom: bd, left: bd, right: bd };
function cell(text, w, head) {
  return new TableCell({ borders, width: { size: w, type: WidthType.DXA },
    shading: head ? { fill: "D5E8F0", type: ShadingType.CLEAR } : undefined,
    margins: { top: 60, bottom: 60, left: 100, right: 100 },
    children: [new Paragraph({ children: [new TextRun({ text, bold: !!head, size: 20 })] })] });
}
function table(widths, rows) {
  return new Table({ width: { size: CW, type: WidthType.DXA }, columnWidths: widths,
    rows: rows.map((r, ri) => new TableRow({ children: r.map((c, ci) => cell(String(c), widths[ci], ri === 0)) })) });
}
const capt = (t) => new Paragraph({ spacing: { before: 60, after: 120 },
  children: [new TextRun({ text: t, italics: true, size: 19 })] });

// ---------- content ----------
const C = [];
// Title
C.push(new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 120 },
  children: [new TextRun({ bold: true, size: 30,
    text: "An Interpretable and Uncertainty-Aware Framework for Lithium-Ion Battery State-of-Health and Remaining-Useful-Life Prognostics on Public Datasets" })] }));
C.push(new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 40 },
  children: [new TextRun({ size: 22, text: "Peixun Wang, Peijun Zhou, Shu Hong, Zhuohua Quan *" })] }));
C.push(new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 40 },
  children: [new TextRun({ italics: true, size: 20, text: "Tianjin Lishen Battery Co., Ltd., Tianjin, China" })] }));
C.push(new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 40 },
  children: [new TextRun({ size: 19, text: "* Correspondence: quanzhuohua@lishen.com.cn" })] }));
C.push(new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 200 },
  children: [new TextRun({ size: 19, text: "ORCID: P. Wang, 0009-0003-4240-9998 (other authors' ORCID iDs to be added at submission)" })] }));

C.push(H1("Abstract"));
C.push(P("Reliable lithium-ion battery state-of-health (SOH) and remaining-useful-life (RUL) estimation underpins the safe, economical operation of electric vehicles and grid storage, yet data-driven prognostics still struggle with three obstacles: limited interpretability, the absence of calibrated uncertainty, and brittleness under distribution shift. We present a framework that addresses these together and evaluate it under strict cell-level, batch-aware protocols on public data spanning two chemistries (the Severson lithium-iron-phosphate corpus and the NASA lithium-cobalt-oxide set), with a third dataset (CALCE LCO) used for a direct transfer test. On a shared set of charge and discharge curve features, including incremental-capacity (IC) descriptors, ridge, support-vector and random-forest regressors are combined with genetic-programming symbolic regression for an interpretable degradation law and split-conformal prediction for empirically calibrated intervals."));
C.push(P("On unseen Severson cells, SOH is estimated at RMSPE 1.26 ± 0.26% with conformal intervals reaching the nominal 90% coverage, and a single IC-peak feature carries most of the model importance; a partial voltage window of only 10 to 20% of the curve retains near-full accuracy, supporting on-board use. A deployable RUL pipeline that uses an out-of-sample SOH estimate (no capacity label at inference) reaches R² = 0.82. Rigorous evaluation also exposes failure modes that single-split studies hide: uncertainty-based active learning does not reliably beat random sampling, and naive cross-batch transfer collapses to negative R²."));
C.push(P("Generalisation is therefore bounded and quantified. A second dataset (NASA, leave-one-cell-out) remains accurate; under streaming cross-batch drift, adaptive conformal recalibration restores near-nominal coverage where static conformal intervals fail; and a direct cross-system test (the LFP and LCO datasets differ in both chemistry and charging protocol) shows that a frozen model collapses while re-fitting the same pipeline recovers, from as little as one labelled target cell for point accuracy, although reliable conformal coverage remains small-calibration-limited and requires additional target calibration cells. This indicates that the re-fitting protocol, rather than a frozen trained model, can be re-targeted across systems with a small labelled target set, while the diagnostics map where such models fail."));
C.push(P("Keywords: lithium-ion battery; state of health; remaining useful life; incremental capacity; active learning; symbolic regression; conformal prediction; adaptive conformal prediction; distribution shift; uncertainty quantification.", { italics: true }));

C.push(H1("1. Introduction"));
C.push(P("Lithium-ion batteries power electric vehicles, consumer electronics and grid-scale storage, and their safe, economical use depends on knowing two quantities in real time: how healthy a cell is, expressed as its SOH, and how much longer it will function, expressed as its RUL. Neither can be measured directly, so models that infer health from observable charge and discharge signals have become the dominant approach. The release of large public cycling datasets, notably the 124-cell fast-charging corpus of Severson et al. [1] and the NASA PCoE ageing set, has accelerated this work and made reproducible benchmarking possible without any in-house experiments [2,3]."));
C.push(P("Three obstacles nonetheless recur. The first is data cost: building a model conventionally requires cycling many cells to end-of-life, which takes months. The second is opacity: the most accurate models are typically black boxes that offer little physical insight and are hard to certify [4]. The third is the absence of calibrated uncertainty: most models report a single number, yet a battery-management system (BMS) making safety- and warranty-critical decisions needs a trustworthy bound on each prediction."));
C.push(P("A deployable prognostic model must be interpretable and uncertainty-aware, and it must be evaluated rigorously enough to reveal where it fails. We therefore study a framework (Figure 1) built on a shared, physically grounded feature representation: feature-based regression models for SOH and RUL, symbolic regression to distil an interpretable closed-form degradation law, and split-conformal prediction to provide empirically calibrated intervals. We additionally test whether uncertainty-based active learning improves labelling efficiency. Throughout, we use cell-level and batch-aware evaluation and report results across two chemistries, so that apparent accuracy is not inflated by optimistic data splitting."));
C.push(P("The central research question of this study is: how can battery SOH and RUL prediction remain interpretable and carry calibrated uncertainty when the data exhibit distribution shift across manufacturing batches and chemistries? Concretely, we test the hypothesis that a shared curve-based feature representation can support accurate SOH and RUL prediction, interpretable degradation-law discovery, and empirically calibrated uncertainty on public cell-level splits, and we ask whether these properties persist under cross-batch evaluation and second-dataset re-application across chemistries. Our contributions are fourfold. (C1) We present a framework that couples interpretable feature-based SOH and RUL regression with symbolic-regression law discovery and split-conformal uncertainty, evaluated under cell-level and batch-aware protocols. (C2) We report a systematic charge and discharge curve feature study, including IC analysis; we show that a single IC peak feature accounts for most of the SOH model importance, and we confirm, under strict cell-level protocols and tied explicitly to the IC-peak mechanism, recent reports that a partial voltage window spanning the phase-transition plateau retains near-full SOH accuracy [5,6,7]. (C3) We provide empirically calibrated conformal prediction intervals for both SOH and RUL, and show that adaptive conformal inference maintains near-nominal coverage under streaming cross-batch drift, where static conformal collapses. (C4) Through multi-seed and batch-aware evaluation, we document and diagnose two failure modes that single-split studies can obscure: the active-learning failure, which we trace to pool homogeneity rather than to a model-specific uncertainty defect, and the cross-batch collapse, which we show is not explained by input-distribution drift alone. A second public dataset further confirms that the same feature-extraction and model-selection protocol remains effective when re-applied to NASA under leave-one-cell-out validation. Finally, a direct LFP-to-LCO transfer test on a third dataset delineates the generalisation boundary: a frozen model does not cross a combined chemistry-and-protocol shift, but the re-fitted pipeline does, with a small and quantified labelling budget."));
fig("fig1_framework.png", "Figure 1. Framework overview, separating the deployable pipeline from the diagnostic modules. The main predictive pipeline (solid path) runs curve features to SOH/RUL models to split-conformal prediction intervals, under an explicit evaluation-protocol layer (cell-level splits, batch-aware transfer, multi-seed reporting, LOCO), with real-data thumbnails (capacity-fade trajectories, an IC curve, a prediction interval drawn to scale). The diagnostic modules (dashed branch) are not part of the deployed pipeline: active learning, symbolic-regression law discovery, cross-batch MMD analysis, adaptive conformal inference, and the LFP-to-LCO transfer test. Outputs are a point prediction, a calibrated interval, and a failure-mode map.", 620, 305).forEach(x => C.push(x));

C.push(H1("2. Related Work"));
C.push(P("Data-driven battery health modelling spans linear and regularised regression, support-vector machines, Gaussian processes, random forests and deep networks; comprehensive reviews survey this rapidly growing field [2], and recent studies estimate capacity or health from engineered charge and discharge curve features, from impedance spectra, and from voltage-relaxation signals [8,9,10]. Quantifying predictive uncertainty, in turn, requires distinguishing aleatoric from epistemic sources [11]. The three studies most directly related to ours typify the prevailing methodology. Roman et al. [12] build a machine-learning pipeline for SOH on 179 cells; they engineer thirty features from charge voltage and current segments with automatic feature selection and adversarial augmentation, report confidence bounds, and reach an RMSPE as low as 0.45%. Wu et al. [13] extract a small set of charging-curve health features and apply ridge regression to joint SOH and RUL estimation. Li et al. [14] construct health indicators by convolving the discharge voltage, reduce dimensionality with principal component analysis (PCA), and optimise a support-vector regression (SVR) model with an improved swarm algorithm, validating on the NASA set. Our framework shares the charge and discharge feature philosophy of these works, but it differs in two ways: it unifies interpretability and calibrated uncertainty in one system, treating sample-efficiency and cross-batch generalisation as questions to be tested rather than assumed, and it is validated across two chemistries."));
C.push(P("Incremental-capacity analysis differentiates capacity with respect to voltage to expose phase-transition peaks whose height, position and area track ageing [15,16,17]. It is a well-established and physically interpretable health indicator, and on-board variants have been combined with support-vector regression for SOH estimation [16]; its relative importance within the present framework is evaluated in Section 5.1. A rapidly maturing line of work estimates SOH from partial voltage segments rather than full cycles: Javaid et al. [5] used mutual information to select discharge-segment ranges for a neural network, Ren et al. [6] built an MI-guided pipeline that reaches roughly 1.3% RMSE from charging segments as narrow as 0.05 V across three chemistries, and Jelovic et al. [7] extracted partial-segment IC features automatically via proper orthogonal decomposition. These studies establish that partial segments suffice and that segment selection can be automated; none of them, however, provides calibrated prediction intervals, batch-aware generalisation tests, or RUL, which is where the present framework differs. Severson et al. [1] showed that the log-variance of the cycle-10-to-100 discharge-curve difference, var(ΔQ(V)), predicts cycle life before noticeable capacity fade, and Attia et al. [18] extended this idea to closed-loop charging optimisation. Our symbolic-regression module recovers the same relationship automatically rather than by manual design. Uncertainty-driven active learning [19], genetic-programming symbolic regression [20,21,22] and distribution-free conformal prediction [23,24] are each individually mature, yet their joint application to battery prognostics, and the comparison of their behaviour across homogeneous and heterogeneous data, has received little attention."));

C.push(table([1560, 1760, 1040, 1600, 1600, 1800], [
  ["Study", "Dataset", "Task", "Model / features", "Calibrated uncertainty", "Cross-batch / 2nd dataset"],
  ["Roman et al.", "MATR + others (179)", "SOH", "RF/DNN, 30 feat.", "Yes (intervals)", "No"],
  ["Wu et al.", "Two public sets", "SOH+RUL", "Ridge, 3 feat.", "No", "No"],
  ["Li et al.", "NASA + lab", "SOH", "SVR, HI + PCA", "No", "No"],
  ["Partial-segment studies (2024-2026)", "Severson/NASA/CALCE/Oxford", "SOH (partial segments)", "MI / POD selection", "No", "No"],
  ["This work", "Severson + NASA", "SOH+RUL", "Explicit formula + importances", "Yes (conformal + ACI)", "Yes (cell/batch-aware)"],
]));
C.push(capt("Table 1. Positioning relative to representative SOH/RUL studies. Among the representative studies compared here, none evaluates interpretability, calibrated uncertainty, and batch-aware or second-dataset performance for both SOH and RUL within a single protocol."));
C.push(H1("3. Datasets and Definitions"));
C.push(H2("3.1 Datasets"));
C.push(P("Three public datasets are used (Table 2): two primary corpora spanning two chemistries, used throughout, and a third (CALCE CS2) used only for the direct cross-system transfer test of Section 5.9. The first is the extended MATR corpus derived from the fast-charging studies of Severson et al. [1] and Attia et al. [18] (LFP/graphite, 1.1 Ah nominal). The original Severson et al. dataset reports 124 commercial cells; the publicly released MATR corpus comprises four batches (2017-05-12, 2017-06-30, 2018-04-12 and 2019-01-24), from which we obtained 182 usable cells after parsing the raw MATLAB v7.3/HDF5 structures and discarding cells with missing or corrupt records. Each cell provides per-cycle summary signals (discharge capacity, internal resistance, charge time and temperature) and linearly-interpolated discharge capacity-voltage curves Q(V) on a common 1000-point voltage grid. We used 140 cells with internal-resistance records (batches 1 to 3) for per-cycle SOH modelling, and 128 cells that reached the end-of-life threshold for RUL. The second dataset, from the NASA Prognostics Center of Excellence (PCoE; [25]; LCO/graphite 18650, 2 Ah nominal), provides four cells (B0005, B0006, B0007 and B0018) with per-cycle voltage, current, temperature, time and measured discharge capacity. Its different chemistry and small cell count make it a demanding second-dataset test. For the direct cross-chemistry transfer experiment (Section 5.9) we additionally use the CALCE CS2 dataset [26]: six prismatic LCO/graphite cells (~1.1 Ah nominal) cycled to end-of-life under constant-current charge and discharge, which we parsed to 4,808 per-cycle discharge curves spanning 2.7 to 4.2 V. Its clean constant-current curves and longer per-cell cycling make it better suited than the four NASA cells to the cell-level, few-shot and conformal evaluation that a transfer test requires."));
C.push(table([2160, 2280, 2160, 2760], [
  ["Property", "Severson (MATR)", "NASA PCoE", "CALCE CS2"],
  ["Chemistry", "LFP/graphite", "LCO/graphite (18650)", "LCO/graphite (prismatic)"],
  ["Nominal capacity", "1.1 Ah", "2 Ah", "~1.1 Ah"],
  ["Batches / cells (raw)", "4 batches; 124 in Severson et al.", "4 cells", "6 cells"],
  ["Usable cells (parsed)", "182", "4", "6"],
  ["Cells for SOH", "140 (batches 1-3, with IR)", "4", "6 (no IR channel)"],
  ["Cells reaching EOL (RUL)", "128", "n/a", "n/a"],
  ["SOH cycle-level samples", "16,800", "625", "4,808"],
  ["RUL cycle-level samples", "15,046", "n/a", "n/a"],
  ["Charge/discharge protocol", "fast-charging", "constant-current", "constant-current"],
  ["Split unit", "cell-level", "leave-one-cell-out", "cell-level (transfer)"],
  ["Per-cycle signals", "Q(V), IR, charge time, T", "V, I, T, capacity", "V, I, Q"],
  ["Role in this study", "primary: SOH, RUL, diagnostics", "second-dataset LOCO", "LFP-to-LCO transfer / few-shot / calibration"],
]));
C.push(capt("Table 2. Summary of the three public datasets and the cell and sample counts used in each task. Severson (MATR) is the primary corpus; NASA is the second-dataset leave-one-cell-out test; CALCE CS2 is used only for the direct LFP-to-LCO transfer experiment (Section 5.9). The original Severson et al. study reports 124 cells; the released MATR corpus yields 182 usable cells after parsing, of which 140 (batches 1 to 3, which carry internal-resistance records) were used for SOH and 128 (those reaching end-of-life) for RUL. CALCE has no internal-resistance channel, so its SOH features are curve-based only."));
C.push(H2("3.2 SOH, EOL and RUL definitions"));
C.push(P("State of health is defined relative to the cell's initial capacity, SOH(k) = Qd(k)/Q0, where Q0 is the median discharge capacity of the first ten valid cycles. End-of-life (EOL) is the cycle at which capacity first reaches 80% of nominal capacity (0.88 Ah for the LFP cells). The remaining useful life at cycle k is RUL(k) = k_EOL - k. SOH and EOL use different reference capacities by design: because the Severson cycle-life label is defined relative to nominal capacity, EOL was kept consistent with that label, whereas SOH was normalised by the early-cycle median capacity to reduce the influence of cell-to-cell variation in initial capacity. RUL therefore qualifies a cell whenever its capacity reaches 0.88 Ah within the recorded window, which 128 of the 140 SOH cells satisfy."));

C.push(H1("4. Methodology"));
C.push(H2("4.1 Feature engineering from charge/discharge curves"));
C.push(P("For each cycle we extracted health indicators (HIs) from the available laboratory charge and discharge records, in three groups; several of these descriptors could in principle be estimated from sufficiently informative on-board voltage-current records, and we examine partial-cycle observation explicitly in Section 5.7; noisy-sensor and pack-level deployment are left to future work. The summary HIs (five) are charge time, internal resistance, and the average, maximum and minimum temperature. The discharge-voltage-curve shape features (six) are the fraction of capacity released once the cell voltage has fallen to fixed thresholds (3.3, 3.2, 3.1, 3.0 and 2.8 V for LFP), together with the median discharge voltage. Because these are normalised, they encode curve shape rather than absolute capacity and therefore avoid label leakage. The incremental-capacity (IC) features (four) were derived from the IC curve |dQ/dV|, obtained by numerical differentiation of Q(V) followed by Savitzky-Golay smoothing ([27]; window length 51 points on the 1000-point grid, polynomial order 3): the peak height, its voltage position, its full-width at half-maximum, and the IC area in the LFP plateau window. The IC peak is robust to the smoothing choice, with Spearman rank correlation above 0.99 across window lengths of 21 to 51 points and polynomial orders 2 to 3, and a per-sample coefficient of variation with a median below 1% (95th percentile 1.5%) (Supplementary Table S1). As Figure 2 shows for a representative cell, the IC peak falls and shifts as the cell ages, and the magnitude of the curve difference ΔQ(V) increases over ageing cycles, which motivates the variance feature."));
fig("fig2_ic_curves.png", "Figure 2. Feature definitions on a representative cell, with curve families coloured continuously by cycle number (colour bars). (a) The IC |dQ/dV| family drops and shifts with ageing; annotations mark the four IC features (peak height, peak position, FWHM, and the shaded IC-area window). (b) The ΔQ(V) = Q_cyc - Q_early family grows in magnitude with ageing, motivating the var(ΔQ) feature. (c) Curve-shape features: capacity fractions at the five voltage thresholds (dashed guides) and the median discharge voltage (red marker).", 620, 196).forEach(x => C.push(x));
C.push(H2("4.2 SOH estimation models"));
C.push(P("SOH was regressed from the 15 HI features using three representative algorithms, implemented in scikit-learn [28]: ridge regression (regularisation α = 1), support-vector regression with an RBF kernel ([29]; C = 10, ε = 0.005, γ set by the scale heuristic), and a random forest ([30]; 300 trees, minimum two samples per leaf). To prevent same-cell leakage, all splits were made at the cell level, so cells in the test set never appear in training; for the ablation we report the mean and standard deviation over five random cell-level splits. Features were standardised on the training partition only. Each cycle was treated as an equally weighted sample, so longer-lived cells contribute proportionally more cycle-level points; we did not reweight by cell and note this as a possible source of bias toward long-lived cells."));
C.push(H2("4.3 Active learning for sample-efficient model building"));
C.push(P("We tested whether active learning reduces the number of cells that must be cycled. Model building was cast as pool-based active learning on the homogeneous batches 1 and 2 (94 cells, cycle-life target). From a random labelled seed of six cells, a random-forest surrogate was fitted; the unlabelled pool was ranked by predictive uncertainty, defined as the standard deviation across the forest trees; and the three most uncertain cells were revealed per acquisition round. Performance was evaluated before each acquisition, at labelling budgets from 6 to 39 cells (eleven acquisitions). We compared this strategy against random sampling at equal labelling budget, repeated the whole procedure over twelve random seeds, and report the mean and standard deviation of the test R² at each budget (Figure 5)."));
C.push(H2("4.4 Symbolic regression for interpretable degradation laws"));
C.push(P("To obtain a human-readable degradation law, we applied genetic-programming symbolic regression (gplearn; [31]) to predict log-cycle-life from the engineered features, with the function set {+, -, ×, ÷, √, log, inverse} and a parsimony penalty; log denotes the natural logarithm. The evolved program was converted to a closed-form expression. Because genetic programming recovers structure but not well-calibrated coefficients, we applied a one-parameter linear calibration of the evolved expression on the training set, and all parity plots are shown in cycle-life units unless otherwise stated."));
C.push(H2("4.5 Conformal prediction intervals"));
C.push(P("Point predictions were augmented with prediction intervals through split-conformal prediction [23,24]. The training cells were partitioned, at the cell level, into a proper-training set and a calibration set. The model was fitted on the former, and absolute residuals r = |y − ŷ| were computed on the calibration cells. Let k = ⌈(n_cal + 1)(1 − α)⌉, where n_cal is the number of calibration residuals; q is the k-th smallest residual, capped at the largest residual when k exceeds n_cal, and the interval is ŷ ± q. This gives marginal coverage at level 1 − α under exchangeability of the calibration and test points. Because cycle-level samples from the same cell are strongly correlated, we calibrated and tested at the cell level and report empirical coverage as the operative quantity, rather than claiming a strict per-prediction guarantee. For comparison, we also report a heuristic tree-quantile interval spanning the 5th to 95th percentile of the random-forest tree predictions."));
C.push(H2("4.6 RUL prediction"));
C.push(P("RUL was regressed from the HI features following an SOH-to-ageing-model-to-RUL pathway, and we evaluated three input settings that differ only in how the SOH input is obtained: (i) curve features only, requiring no capacity label at inference; (ii) an end-to-end setting in which the SOH input is an out-of-sample prediction from a SOH model trained only on the training cells; and (iii) an oracle, SOH-assisted setting in which the SOH input is the measured, capacity-derived value. Unless stated otherwise, deployable performance refers to settings (i) and (ii), which use no measured capacity at inference; setting (iii) is reported only as an upper bound that quantifies the optimism introduced by a perfect SOH label. The main RUL figure (Figure 4) therefore shows the end-to-end setting (ii), with the oracle overlaid for comparison. Cell-level splitting and conformal intervals were applied as above."));

C.push(H1("5. Results"));
C.push(H2("5.1 SOH estimation and feature ablation"));
C.push(P("On one held-out cell-level split, used for visualisation, the random forest achieved the best accuracy (RMSPE 1.04%, mean absolute error (MAE) 0.59% SOH, R² = 0.964), ahead of SVR (1.28%, R² = 0.944) and ridge regression (2.35%, R² = 0.823) (Table 3; Figure 3a,c,d). Across five random cell-level splits, the same full 15-feature random forest achieved R² = 0.933 ± 0.03; the difference from the single-split value reflects split-to-split variation, not a different model. A feature ablation over these five splits (Table 4) showed a clear progression: summary HIs alone reached R² = 0.654 ± 0.08; adding the discharge-curve shape features raised this to R² = 0.919 ± 0.04; and adding the IC features gave the full model at R² = 0.933 ± 0.03. The single IC peak-height feature accounted for 0.88 of the random-forest impurity importance, the largest of any feature on this dataset. A permutation-importance analysis, measured as the decrease in test R² after permuting each feature and averaged over five cell-level splits, confirmed this ranking: permuting the IC peak feature reduced the test R² by 0.94, far more than any other feature, and it retained the largest importance under both impurity and permutation measures (Supplementary Figure S1); the per-batch correlation structure of all 15 HIs with SOH is mapped in Supplementary Figure S3. This identifies incremental-capacity analysis as a strong and physically interpretable health indicator. For comparison, a multilayer perceptron baseline was unstable under cell-level splitting (R² = -0.5 ± 1.2 over five splits). We read this as a limitation of the present cell count rather than evidence that deep models are inherently unsuitable: no extensive regularisation tuning was attempted, and recurrent and Transformer models operating on raw cycle sequences [32,33] remain a systematic comparison for future work (Section 6)."));
C.push(table([3360, 2000, 2000, 2000], [
  ["Model", "RMSPE (%)", "MAE (% SOH)", "R²"],
  ["Ridge", "2.35", "1.36", "0.823"],
  ["SVR-RBF", "1.28", "0.74", "0.944"],
  ["Random forest", "1.04", "0.59", "0.964"],
]));
C.push(capt("Table 3. SOH estimation on unseen cells (Severson, single cell-level split, for visualisation only; refer to Table 4 for multi-split statistics, which are the primary results)."));
C.push(table([3360, 2000, 2000, 2000], [
  ["Feature set", "RMSPE (%)", "MAE (% SOH)", "R²"],
  ["Summary HIs (5)", "2.91 ± 0.24", "1.86 ± 0.16", "0.654 ± 0.08"],
  ["+ curve shape (11)", "1.40 ± 0.27", "0.71 ± 0.12", "0.919 ± 0.04"],
  ["+ IC (15, full)", "1.26 ± 0.26", "0.68 ± 0.12", "0.933 ± 0.03"],
]));
C.push(capt("Table 4. Feature-group ablation (random forest, 5 seeds, mean ± s.d.)."));
C.push(H2("5.2 Calibrated uncertainty"));
C.push(P("Split-conformal intervals achieved 90.0% empirical coverage at the 90% nominal level, with a mean half-width of 1.50 percentage points of SOH, whereas the heuristic tree-quantile interval under-covered at 84.9%; the reliability diagram in Figure 3b shows that the conformal intervals track the ideal diagonal across all nominal levels while the tree-quantile heuristic under-covers throughout. The conformal interval thus provided better empirical calibration than the heuristic on this held-out split, which is a prerequisite for safety-relevant decision support, though not by itself sufficient for on-board deployment."));
fig("fig3_soh_panels.png", "Figure 3. SOH estimation on unseen cells (visualisation split, random forest). (a) Test-cell trajectories with 90% split-conformal prediction intervals; each cell is coloured individually and the legend reports its RMSPE. (b) Reliability diagram: observed versus nominal coverage for split-conformal and tree-quantile intervals against the ideal diagonal; (c) parity of predicted versus true SOH; (d) prediction-error distribution.", 620, 472).forEach(x => C.push(x));
C.push(H2("5.3 RUL prediction"));
C.push(P("Under the nominal-capacity EOL definition, 128 cells qualified, giving 15,046 cycle-level samples; the target RUL had a median of 337 cycles and ranged from 0 to 1933. To separate the deployable performance of RUL prediction from the optimism introduced by using measured SOH, we compared three input settings over five cell-level splits (Supplementary Table S2). A model using only the curve features, with no capacity label at inference, reached R² = 0.87 (MAE 65 cycles, 19% of the median RUL); supplying an out-of-sample SOH estimate gave R² = 0.82; and supplying the measured SOH as an oracle gave R² = 0.88 (MAE 59 cycles). The oracle therefore inflates performance only modestly, and a fully deployable model that needs no capacity measurement still predicts RUL with R² = 0.87. To reflect deployable performance rather than the oracle, the main RUL figure shows the end-to-end model, whose SOH input is an out-of-sample prediction (a SOH model trained on the training cells and applied to the held-out cells), not the measured capacity. On a single split this end-to-end model reached R² = 0.83 (MAE 74 cycles), and its 90% conformal intervals achieved 92.3% empirical coverage with a mean half-width of 203 cycles (Figure 4); the oracle trajectory using measured SOH (single-split R² = 0.90, MAE 50 cycles) is overlaid for comparison and is only modestly tighter, visually confirming that the deployable pipeline does not collapse when the measured label is withheld. Accuracy was strongly horizon-dependent: end-to-end MAE was 37 cycles for RUL below 100 cycles, rising to 130 cycles beyond 700, while the conformal half-width is fixed, so the intervals are widest relative to the error precisely near end-of-life; the same horizon dependence is illustrated for the SOH-assisted model in Supplementary Figure S4. In the SOH-assisted model the local degradation rate had the largest feature importance (0.67)."));
fig("rul_curves.png", "Figure 4. End-to-end RUL prediction on unseen test cells: the SOH input is an out-of-sample prediction, not the measured value. Blue points are the deployable end-to-end prediction with its 90% split-conformal interval (shaded); the black line is the true RUL trajectory (k_EOL - k); the grey dashed line is the oracle model using measured SOH, shown only for comparison.", 620, 333).forEach(x => C.push(x));
C.push(H2("5.4 Active-learning sample efficiency"));
C.push(P("On the homogeneous batches 1 and 2, uncertainty-based active learning and random sampling were indistinguishable within seed-to-seed variability across the labelling budget, with all differences well within one standard deviation over twelve seeds (Figure 5). At 39 revealed cells the two strategies reached R² = 0.71 ± 0.15 (active) and R² = 0.71 ± 0.13 (random), and random sampling was marginally ahead at most intermediate budgets. A single split can make active learning appear to win, but that apparent advantage did not survive seed averaging. The null result was robust to the initial seed size: increasing it from 6 to 12 to 18 cells left the two strategies indistinguishable in every case, with differences within one standard deviation (Supplementary Table S3). Uncertainty sampling therefore provided no reliable labelling-efficiency benefit here, a negative result that we interpret alongside the batch-effect findings in Section 6."));
fig("battery_learning_curve.png", "Figure 5. Active learning (uncertainty sampling) versus random sampling for cycle-life prediction on homogeneous cells (batches 1-2), mean ± s.d. over 12 seeds. The two strategies overlap within run-to-run variability (shaded ± s.d. bands) across the labelling budget.", 560, 368).forEach(x => C.push(x));
C.push(H2("5.5 Interpretable degradation law"));
C.push(P("Given 9 to 15 features, symbolic regression selected var(ΔQ) as the sole predictor on the pooled data. After a one-parameter linear calibration, the evolved expression log L = 0.96(-v_dQ + 1.99 - 2.72/v_dQ) + 0.21 reached a log-scale R² of 0.69 on the full pooled data (Figure 6, plotted in cycle-life units) and 0.63 on a held-out cell split, comparable to the hand-crafted variance model (0.65). Here v_dQ denotes the base-10 logarithm of the variance of ΔQ(V) between cycles 10 and 100; in our data it is of order -4, so the expression is not interpretable in raw physical units and the 1/v_dQ term stays well away from any singularity. When var(ΔQ) was offered among the candidate features, the search therefore reproduced the main empirical relationship reported by Severson et al. [1], rather than deriving it from first principles. On the homogeneous batches 1 and 2 it found a richer multi-feature expression reaching log-R² = 0.85, above the single-feature variance model (0.58). We emphasize that the symbolic-regression module identifies a known empirical relationship rather than deriving a novel physical law: the evolved expression contains a 1/v_dQ term with no clear physical meaning, and the result is best read as a compact data-fitting form. At the same time, the autonomous selection of var(ΔQ) from fifteen candidates demonstrates that data-driven structure search can automate a piece of feature engineering that originally required expert insight."));
fig("fig7_sr_parity.png", "Figure 6. Parity plot of the calibrated symbolic-regression formula versus true cycle life (pooled-data fit; the held-out-split result is reported in the text).", 380, 380).forEach(x => C.push(x));
C.push(H2("5.6 Cross-dataset validation and batch effects"));
C.push(P("Using the same feature-extraction and modelling protocol, we evaluated the framework on NASA under leave-one-cell-out (LOCO) validation. Ridge regression was the most accurate here, with a mean RMSPE of 2.48% and an overall R² of 0.955, ahead of the random forest (4.18%, R² = 0.875) and SVR (5.42%, R² = 0.789) (Table 5; Figure 7). This reversal of the Severson ranking suggests that simpler linear models can be more robust when very few cells are available, although, with only four cells, the NASA comparison is an initial indication of method applicability rather than a statistical conclusion, since a single anomalous cell could shift the ranking. Finally, although a batch-mixed 5-fold cross-validation gave R² = 0.80, training on batches 1 and 2 and testing on batch 3 collapsed to R² = -0.28, and testing on the 2019 batch to R² = -1.93. Naive pooling of heterogeneous batches therefore masked a severe cross-distribution failure that our cell-level and batch-aware protocols were designed to expose. The full 4-by-4 transfer matrix (Figure 8a) makes the pattern explicit: within-batch accuracy (diagonal, R² 0.46 to 0.74) coexists with erratic off-diagonal transfers ranging from R² = 0.49 down to -2.51, while the corresponding feature-distribution distances (Figure 8b) vary smoothly; the visual mismatch between the two panels anticipates the drift analysis of Section 6."));
fig("fig8_transfer_mmd.png", "Figure 8. Cross-batch transferability versus distribution distance. (a) Transfer R² for every train-test batch pair (diagonal: within-batch cell-level cross-validation); (b) maximum mean discrepancy (MMD) between batch feature distributions. The erratic transfer pattern in (a) contrasts with the smooth distance structure in (b), showing that input-distribution drift alone does not predict transfer success.", 620, 259).forEach(x => C.push(x));
C.push(table([3360, 2000, 2000, 2000], [
  ["Model (NASA, LOCO)", "Mean RMSPE (%)", "Overall R²", "Overall MAE (%)"],
  ["Ridge", "2.48", "0.955", "1.66"],
  ["SVR-RBF", "5.42", "0.789", "3.23"],
  ["Random forest", "4.18", "0.875", "2.56"],
]));
C.push(capt("Table 5. Second-dataset SOH on NASA under leave-one-cell-out (LOCO) validation. Mean RMSPE is averaged over the four held-out cells; overall R² and MAE are computed on the concatenated out-of-fold predictions."));
fig("nasa_soh_curves.png", "Figure 7. Second-dataset SOH on NASA under leave-one-cell-out validation: predicted versus true degradation for the four cells, shown for ridge regression, the best-performing model on NASA (Table 5); each panel title reports the per-cell RMSPE.", 600, 382).forEach(x => C.push(x));

C.push(H2("5.7 Partial voltage-window features for on-board deployment"));
C.push(P("Electric-vehicle battery management rarely observes a full charge or discharge cycle, and recent studies have shown that partial voltage segments suffice for SOH estimation [5,6,7]. Rather than claiming this observation as new, we verify that it holds within our framework, under strict cell-level splitting, and connect it to the IC-peak mechanism identified in Section 5.1. From each discharge curve we extracted the local IC peak, the capacity delivered in the window, and the median voltage within a voltage window of varying width and position, and re-trained the SOH model on these window features together with the summary HIs (Figure 9). A window covering only 10% of the voltage span, centred on the LFP phase-transition plateau, already reached R² = 0.90, against 0.94 for the full curve; a 20% window reached the same level, and accuracy then rose only gradually with width (Figure 9a). The window position was decisive. A 20% window centred on the plateau (3.1 to 3.3 V) gave R² = 0.90 to 0.92, whereas the same window placed in the low-voltage region (2.8 V) fell to 0.78 (Figure 9b). A practical guideline follows: an on-board SOH estimate of near-full-curve quality needs only a short voltage segment, provided that segment spans the phase-transition plateau where the incremental-capacity peak resides. The window need not be chosen by hand: consistent with the MI-guided selection of Javaid et al. [5] and Ren et al. [6], a scan that ranks candidate windows by the mutual information between their features and SOH automatically selects the plateau-adjacent region (MI peak at 3.1 V, accuracy peak at 3.0 V), in agreement with the heuristic choice (Supplementary Figure S5). Our scan is coarser than the 0.05 V segments of Ren et al. [6]; its purpose here is to tie the informative band to the IC-peak mechanism and to confirm the partial-window result under the cell-level and uncertainty-aware protocols of this framework, which the prior partial-segment studies do not address. We are deliberately careful about the scope of this result: the partial-window accuracy reported here is established within distribution (cell-level held-out cells of the same chemistry), and the adaptive-conformal calibration that keeps coverage near nominal under drift (Section 5.8) was demonstrated separately, on full-curve features under cross-batch streaming. The two are complementary deployability properties of the same framework rather than a single jointly validated result; the distribution-free nature of conformal calibration means it can in principle wrap a partial-window estimator and adapt its interval as the population drifts, but explicitly stress-testing a narrow-window model under cross-batch or cross-system drift, with adaptive conformal intervals, is a natural and important extension that we have not performed here and leave to future work."));
fig("supp_partial_window.png", "Figure 9. Partial voltage-window SOH estimation (random forest, five cell-level splits, mean ± s.d.). (a) SOH R² versus window width, with the window centred on the LFP plateau; a 10 to 20% window already approaches the full-curve accuracy. (b) SOH R² versus the centre voltage of a fixed 20% window; accuracy is high only when the window covers the phase-transition plateau (3.1 to 3.3 V, shaded).", 620, 238).forEach(x => C.push(x));
C.push(H2("5.8 Adaptive conformal inference under cross-batch drift"));
C.push(P("The split-conformal intervals of Section 5.2 assume exchangeability, which the cross-batch drift of Section 5.6 violates. We therefore streamed cells in batch order, with the point model trained and the interval calibrated only on the first batch, and compared three interval strategies that differ in the information they may use: static split-conformal (no updates after calibration), rolling recalibration (the same online residual stream as ACI, but a fixed α = 0.10), and adaptive conformal inference (ACI; [34]), which additionally adapts α from coverage feedback. The rolling baseline makes the comparison information-equal and separates the value of online data from the value of α-adaptation. Static conformal collapsed under the drift (8% coverage on the next batch, 36% overall against the 90% target). Rolling recalibration, with the same online information as ACI, recovered most of the loss (70 to 89% per batch, 82% overall, mean width 0.83 in log-life units). ACI closed the remaining gap, reaching 84 to 91% per batch and 89% overall, at the cost of wider intervals (mean width 1.07) (Figure 10). Most of the benefit therefore comes from online recalibration itself; the adaptive α contributes the final margin to near-nominal coverage. We also note an important caveat: because the underlying point model is itself degraded under this drift (Section 5.6), the calibrated intervals are wide. Conformal calibration keeps the uncertainty honest, correctly signalling that the model is out of its depth, but it does not restore the decision utility of an uninformative predictor; pairing online calibration with domain adaptation of the point model is the natural next step."));
fig("supp_aci.png", "Figure 10. Adaptive conformal inference under cross-batch drift, with an information-equal baseline. Cells are streamed in batch order with the model and calibration fixed on the first batch. (a) Static split-conformal (orange) collapses far below the nominal 90% (dashed); rolling recalibration with the same online residuals but fixed α (green) recovers most of the coverage; ACI (blue) reaches near-nominal by additionally adapting α. Rolling window of 25 cells. (b) Interval widths: static stays fixed, while the online methods widen honestly as residuals grow and narrow again on the closer batch 4.", 520, 403).forEach(x => C.push(x));
C.push(H2("5.9 Cross-system generalization (chemistry and protocol): direct LFP-to-LCO transfer"));
C.push(P("The cross-batch analysis (Section 5.6) showed that a model can fail on data drawn from a shifted distribution of the same chemistry. A stronger test is direct transfer across chemistries. We therefore trained the SOH model on the Severson LFP cells and applied it to an independent LCO dataset, the six prismatic CALCE CS2 cells (Section 3.1), parsed to 4,808 per-cycle discharge curves. Crucially, the two public datasets differ not only in cathode chemistry (LFP versus LCO) but also in charging protocol (multi-step fast-charging versus constant-current) and test temperature; this transfer therefore probes a combined, system-level shift, and the present design cannot attribute the outcome to chemistry alone (we return to this confound in Section 6). The chemistry difference is concrete at the feature level: the LCO incremental-capacity peak sits near 3.68 V, far from the 3.2 V LFP plateau on which the feature windows of Section 5.1 were defined, so absolute-voltage features computed on LFP have a different physical meaning on LCO. We compared four settings, all evaluated on held-out LCO cells (Table 6, Figure 11): (i) zero-shot, the frozen LFP-trained model applied to LCO; (ii) re-fit with native, data-driven feature windows, under cell-level splitting and multi-seed evaluation; (iii) re-fit while keeping the fixed LFP windows, to separate the effect of window placement from that of model transfer; and (iv) few-shot re-fitting on a small number N of labelled LCO cells."));
C.push(P("The result is unambiguous and graded. The frozen LFP model does not transfer: zero-shot SOH reaches only R² = 0.06 (RMSPE 15.6%), predicting close to a constant value regardless of true SOH (Figure 11c). Re-fitting the same pipeline on LCO recovers most of the performance (R² = 0.90 ± 0.06, RMSPE 4.5%), and its split-conformal intervals, calibrated on a held-out LCO cell, reach 89% empirical coverage at the 90% level. Adaptation is inexpensive: a single labelled LCO cell already lifts R² to 0.84, and three cells to 0.85 (Figure 11b). Re-fitting with the original LFP windows performs as well as with native windows (R² = 0.89 versus 0.90), which localizes the cause: it is the trained model, not the feature definition, that fails to cross chemistries; once the model is re-fit on the target chemistry, even imperfectly placed feature windows carry enough degradation signal for a tree ensemble to relearn the mapping. This refines our initial expectation that window mislocation would dominate the failure."));
C.push(P("This is the honest reading of framework universality. A single trained model is chemistry-specific and should not be claimed to transfer zero-shot; what transfers is the methodology, namely the feature pipeline together with the cell-level and conformal protocols, which re-targets to a new chemistry with a small, quantified labelling budget. The pattern is consistent with the cross-batch collapse of Section 5.6: both are concept-drift failures of a fixed feature-to-life mapping, here across a combined chemistry-and-protocol (system-level) change rather than across a manufacturing batch. Two limits should be stated plainly. First, only six LCO cells were available, so the LCO error bars are wider and its RMSPE (4.5%) is higher than on LFP (1.26%). Second, the conformal calibration is itself small-sample-limited, and we quantified this directly with a calibration-cell sweep (Table 6): with a single calibration cell the empirical coverage is unstable (83 ± 8% across seeds), it recovers toward the 90% target with two cells (88 ± 4%, with a tighter spread), and three calibration cells over-cover (95 ± 2%) at the cost of starving the fit (R² falls from 0.93 to 0.78). Increasing the calibration set therefore does restore coverage from the degenerate single-cell case, but with only six cells it trades against fitting data; both limits are consequences of small N, not of the method, and neither affects the central, deliberately falsifiable finding, that zero-shot fails and re-fit recovers, which would have been equally reportable had re-fitting also failed."));
C.push(table([3360, 1500, 1620, 2280], [
  ["Setting (LCO target, held-out cells)", "R²", "RMSPE (%)", "Conformal coverage"],
  ["Zero-shot (frozen LFP model)", "0.06", "15.6", "n/a"],
  ["Re-fit (LFP feature window)", "0.89", "4.5", "91%"],
  ["Re-fit (native feature window)", "0.90", "4.5", "89%"],
  ["Few-shot, 1 labelled LCO cell", "0.84", "6.5", "21% (degenerate)"],
  ["Few-shot, 3 labelled LCO cells", "0.85", "5.8", "71%"],
  ["Calibration sweep, 1 calibration cell", "0.93", "—", "83 ± 8%"],
  ["Calibration sweep, 2 calibration cells", "0.92", "—", "88 ± 4%"],
  ["Calibration sweep, 3 calibration cells", "0.78", "—", "95 ± 2%"],
]));
C.push(capt("Table 6. Direct cross-system (LFP-to-LCO) transfer and small-sample conformal calibration (CALCE CS2). R² and RMSPE are on held-out LCO cells; re-fit and few-shot values are means over five cell-level splits. Zero-shot uses the frozen LFP model with no LCO labels. Conformal coverage is at the 90% nominal level with cell-level calibration. Few-shot coverage is reported despite small-calibration degeneracy (one calibration cell gives unreliable coverage). The calibration sweep (two held-out test cells, eight seeds) isolates the calibration-set size: coverage recovers from the unstable single-cell case (83 ± 8%) toward nominal with two cells (88 ± 4%), while dedicating three of the six cells to calibration over-covers (95 ± 2%) and starves the fit (R² 0.93 to 0.78), making the small-sample trade-off explicit. RMSPE is not reported for the sweep, which varies the calibration partition rather than the model."));
fig("crosschem_result.png", "Figure 11. Direct cross-system transfer (chemistry and protocol), LFP to LCO (CALCE CS2). (a) SOH R² on held-out LCO cells: the frozen LFP model collapses (red) while re-fitting the pipeline on LCO recovers, with native and LFP feature windows tying. (b) Adaptation budget: R² versus the number of labelled LCO cells, against the full re-fit (dashed) and zero-shot (dotted) references; even one cell recovers most of the gap. (c) Predicted versus true SOH for a held-out LCO cell (CS2_38): zero-shot predictions collapse to a near-constant band, whereas the re-fit model tracks the diagonal.", 620, 190).forEach(x => C.push(x));
C.push(H1("6. Discussion"));
C.push(P("Interpretability and the role of IC features. The ablation and the feature-importance analysis together support a physically plausible interpretation of the model. Summary indicators alone are weak (R² = 0.65); the shape of the discharge voltage curve carries most of the signal (R² = 0.92); and IC descriptors refine it further (R² = 0.93), with the IC peak height accounting for 0.88 of the random-forest importance. This pattern is consistent with the electrochemistry, since loss of active material and of lithium inventory both attenuate and shift the LFP phase-transition peak ([35,36]; Figure 2). The symbolic-regression result points the same way: given fifteen candidate features, the search selected var(ΔQ) and recovered a known empirical degradation relationship when that feature was present, rather than deriving it from first principles."));
C.push(P("Why calibrated uncertainty matters. Our point accuracy (RMSPE 1.26 ± 0.26%) is competitive with the literature, but the more deployment-relevant property is interval calibration. Split-conformal intervals reached 90.0% empirical coverage at the 90% level, against 84.9% for an uncalibrated heuristic. For battery-management decision support, calibrated prediction intervals are preferable to uncalibrated point estimates, but additional validation under on-board sensing and pack-level conditions is still required before deployment, even though the partial-window analysis (Section 5.7) already indicates robustness to incomplete cycles."));
C.push(P("Active learning did not provide a reliable benefit. On homogeneous data, uncertainty sampling matched random sampling once results were averaged over twelve seeds, and a single split could create a misleading impression of superiority (Figure 5). We diagnosed this null result (Supplementary Table S4). The random-forest and Gaussian-process uncertainty estimates correlated only weakly with the actual prediction error (Spearman 0.37 and 0.24), and replacing the random forest with a Gaussian-process surrogate [37], whose uncertainty is in principle better calibrated, did not recover an advantage (R² = 0.73 ± 0.20 against 0.69 ± 0.18 for random sampling). Because changing the model does not help, the failure is most consistent with pool homogeneity: on these similar cells, informativeness varies too little for any acquisition rule to exploit, which also explains the weak uncertainty-error correlation. This null result is a useful counterpoint to the common assumption that uncertainty sampling is always preferable, and it reinforces the broader theme that apparent gains must be checked against seed and split variation. We note the converse possibility: on genuinely heterogeneous fleet data, where informativeness varies widely across cells, acquisition rules that reward diversity or representativeness rather than raw uncertainty may yet deliver the labelling-efficiency gains that were absent here; comparing them is a natural follow-up."));
C.push(P("Batch effects as a hidden hazard. The gap between a batch-mixed cross-validation (R² = 0.80) and genuine cross-batch transfer (R² from -0.28 to -1.93) is the most cautionary result. A model that looks excellent under random splitting can fail completely on a new batch or chemistry. This motivates our consistent use of cell-level and batch-aware evaluation, and it echoes the small-data NASA result, where the simplest model generalised best. Reporting protocols should therefore state the train and test partitioning explicitly, because that choice silently determines whether a reported accuracy reflects deployable performance. To probe the cause, we measured the input-feature distribution distance between batches with the radial-basis-function maximum mean discrepancy (MMD; [38]). MMD correlated only weakly with single-batch transfer R² (Spearman 0.30), and no MMD threshold cleanly separated successful from failed transfers (Figure 8; scatter view in Supplementary Figure S2). Covariate shift alone therefore does not explain the collapse. The remaining candidates are concept drift, that is, a shift in the feature-to-life mapping between charging-policy families, a shift in the label distribution itself (batch cycle lives differ systematically; Supplementary Figure S6), and the instability of single-batch training on roughly forty cells; these appear to contribute more than input-distribution drift alone, possibly compounded by batch-to-batch differences in charging protocol. This argues for label-aware domain adaptation rather than input-distribution matching alone [39], which is left to future work. Crucially, this collapse and the active-learning null result of Section 5.4 are two faces of the same underlying limitation rather than isolated negatives. The within-batch homogeneity that we identified as the reason uncertainty sampling cannot outperform random selection, because informativeness varies too little across near-identical cells, simultaneously means that a model trained within one batch sees a narrow slice of the population and has little pressure to learn features that remain valid outside it. A pool that is too homogeneous for acquisition to exploit is, by the same token, too homogeneous to train a model that survives the distribution shift of a new batch or chemistry. Read together, the two diagnostics describe a single mechanism: a single batch under-samples the operating population that a deployed model must serve, which is precisely why both within-batch acquisition gains and cross-batch transfer fail, and why genuine progress requires more diverse training data or explicit domain adaptation rather than a cleverer acquisition rule on a homogeneous pool."));
C.push(P("Alternative explanations and failure modes. Several findings admit more than one reading. The dominance of the IC peak may partly reflect the sharp LFP phase-transition plateau rather than a universal property of SOH, so the feature ranking could differ for other chemistries. The absence of an active-learning gain may stem from miscalibrated small-sample uncertainty as much as from genuine pool homogeneity. The strong NASA performance of ridge regression rests on only four cells and noisy capacity labels, so it should be read as suggestive rather than conclusive. Finally, the conservative coverage of the RUL intervals likely reflects residual heteroscedasticity across prediction horizons, which Supplementary Figure S4 makes explicit: absolute errors grow several-fold from short to long horizons while the conformal half-width is constant."));
C.push(P("Limitations. Our point accuracy does not yet match the 0.45% RMSPE of Roman et al. [12], who use thirty features and adversarial augmentation; closing this gap is left to future work. The NASA validation, although standard, involves only four cells. Direct cross-chemistry transfer (Section 5.9) confirms that a frozen model does not cross chemistries and must be re-fit on the target; this re-fit was demonstrated on only six LCO cells, so the LCO error bars are wide and a larger multi-chemistry study is needed to map the adaptation budget precisely. A further open question is to disentangle chemistry shift from operating-condition shift (temperature, depth-of-discharge and C-rate), which would require a dataset that varies both axes within a common protocol, such as the Sandia multi-chemistry cycling corpus; its complete per-step time series is not openly downloadable and must be requested from the data provider, so this separation is left to future work. We also did not benchmark recurrent or Transformer models on raw cycle sequences [32,33]; a multilayer perceptron on the tabular features was unstable at this cell count (Section 5.1), and temporal deep models, which typically require more cells, are a natural extension once larger datasets are pooled. Finally, RUL accuracy remains horizon-dependent, with larger errors far from end-of-life."));

C.push(H1("7. Conclusion"));
C.push(P("We presented an interpretable and uncertainty-aware framework for lithium-ion battery SOH and RUL prognostics and evaluated it under strict cell-level protocols on two public datasets spanning two chemistries. Using only charge and discharge curve features, with a single incremental-capacity descriptor carrying most of the SOH model importance, the framework estimated SOH at RMSPE 1.26 ± 0.26% (R² = 0.933 ± 0.03 over five cell-level splits) and RUL at R² = 0.87 from curve features alone, needing no capacity label at inference (R² = 0.88 with measured SOH as an oracle upper bound). Its split-conformal intervals are empirically calibrated and, in an adaptive form, remain near nominal coverage under cross-batch drift where static conformal collapses, and symbolic regression reproduced an interpretable degradation law. A partial voltage window of only 10 to 20%, spanning the phase-transition plateau, retained near-full SOH accuracy, indicating compatibility with the partial cycles seen in real operation. Equally important, rigorous evaluation exposed two failure modes that single-split studies can hide: uncertainty-based active learning did not reliably beat random sampling, and naive cross-batch transfer collapsed, whereas the same protocol remained effective on NASA under leave-one-cell-out validation. A direct LFP-to-LCO transfer test made the scope of this generalisation explicit: a frozen model collapses under the combined chemistry-and-protocol shift (R² = 0.06) while the re-fitted pipeline recovers (R² = 0.90, 89% coverage) from as little as one labelled target cell, indicating that it is the methodology rather than a single trained model that transfers. Within the evaluated datasets and protocols, the framework therefore offers accurate, calibrated and interpretable prediction, while the cross-batch tests show that random cell-level cross-validation can overstate deployable performance. Future work will add partial-cycle and charge-segment features, study weighted or group-conformal intervals and conformalised quantile regression for the horizon-dependent RUL errors [40,41,42], and pursue label-aware domain adaptation and physics-informed machine learning to close the cross-batch and cross-chemistry gaps identified here."));

C.push(H1("Supplementary Information"));
fig("supp_permutation_importance.png", "Supplementary Figure S1. SOH feature permutation importance on held-out cells (decrease in test R² after permuting each feature, five seeds, mean ± s.d.). Permuting the IC peak feature reduces the test R² by 0.94, far more than any other feature, confirming the impurity-based ranking in the main text.", 480, 377).forEach(x => C.push(x));
C.push(table([3360, 3000, 3000], [
  ["Smoothing setting", "IC peak (mean)", "Spearman rho vs default"],
  ["raw (no smoothing)", "5.74", "0.952"],
  ["window 21, order 2", "5.62", "0.998"],
  ["window 21, order 3", "5.62", "0.998"],
  ["window 31, order 3", "5.61", "0.999"],
  ["window 51, order 3 (default)", "5.52", "1.000"],
]));
C.push(capt("Supplementary Table S1. Sensitivity of the IC peak feature to Savitzky-Golay smoothing, computed on 540 cell-cycle samples. Across window lengths of 21 to 51 points and polynomial orders 2 to 3, the IC peak has Spearman rank correlation above 0.998 with the default (window 51, order 3); even unsmoothed values correlate at 0.95. The per-sample coefficient of variation across smoothing settings has median 0.88% and 95th percentile 1.51%."));
C.push(table([3960, 1800, 1800, 1800], [
  ["RUL input setting", "R² (5 splits)", "MAE (cycles)", "Relative MAE"],
  ["No SOH (curve features only)", "0.866 ± 0.022", "65", "19.4%"],
  ["End-to-end (out-of-sample SOH)", "0.822 ± 0.023", "79", "23.5%"],
  ["Oracle (measured SOH)", "0.881 ± 0.017", "59", "17.4%"],
]));
C.push(capt("Supplementary Table S2. RUL prediction under three SOH-input settings (random forest, five cell-level splits, mean ± s.d.). Relative MAE is normalised by the median RUL of 337 cycles. The deployable no-SOH and out-of-sample-SOH models lose only 0.01 to 0.06 in R² relative to the measured-SOH oracle, showing that the RUL result is not strongly inflated by using measured SOH."));
C.push(table([3360, 2000, 2000, 2000], [
  ["Initial seed (cells)", "Active R²", "Random R²", "Difference"],
  ["6", "0.697 ± 0.143", "0.696 ± 0.161", "+0.001"],
  ["12", "0.694 ± 0.147", "0.682 ± 0.146", "+0.012"],
  ["18", "0.701 ± 0.130", "0.739 ± 0.130", "-0.038"],
]));
C.push(capt("Supplementary Table S3. Sensitivity of the active-learning result to initial seed size (homogeneous batches 1 and 2, random forest, 12 random seeds, mean ± s.d.). Final labelling budgets are 33, 39 and 45 cells for seeds of 6, 12 and 18 respectively (nine acquisitions of three cells each); the main protocol of Figure 6 evaluates up to 39 cells. Increasing the seed from 6 to 18 cells does not give uncertainty sampling a reliable advantage over random sampling; all differences lie within one standard deviation."));
fig("supp_drift_mmd.png", "Supplementary Figure S2. Scatter view of cross-batch drift versus transferability: single-batch transfer R² against MMD for all train-test pairs (companion to Figure 8). The weak association (Spearman 0.30) and the absence of a clean MMD threshold indicate that covariate shift alone does not explain the cross-batch collapse.", 620, 258).forEach(x => C.push(x));
fig("figS3_corr_heatmap.png", "Supplementary Figure S3. Spearman correlation of each of the 15 health indicators with SOH, overall and per batch. The IC peak and the curve-shape fractions correlate strongly and consistently with SOH across batches, complementing the importance ranking of Supplementary Figure S1.", 400, 450).forEach(x => C.push(x));
fig("figS4_rul_horizon.png", "Supplementary Figure S4. RUL error versus prediction horizon (test cells, single split). Bars: MAE per true-RUL bin; orange line: 90th percentile of absolute error; dashed line: the fixed split-conformal half-width (166 cycles). Errors grow with horizon while the interval width is constant, which explains the conservative coverage near end-of-life.", 460, 294).forEach(x => C.push(x));
fig("supp_mi_window.png", "Supplementary Figure S5. Information map for data-driven voltage-window selection. Candidate 0.30 V windows are scanned across 2.3 to 3.4 V; the two colour strips show, as continuous maps over the window-centre voltage, the summed mutual information between the three window features and SOH (top, red) and the cell-level SOH R² of those features (bottom, blue); tick marks indicate the evaluated centres and dashed lines bound the LFP plateau. Both criteria independently select the plateau-adjacent region (MI peak 3.1 V, R² peak 3.0 V), matching the heuristic window of the main text without any manual threshold, and consistent with prior MI-guided segment selection [5,6].", 480, 258).forEach(x => C.push(x));
fig("supp_batch_traj.png", "Supplementary Figure S6. Direct comparison of degradation across batches. (a) Capacity-fade trajectories by batch (thin lines: individual cells; thick lines: batch medians; batches 1-3, which carry per-cycle records); (b) cycle-life distributions for all four batches. The label distribution itself shifts strongly across batches (median life 483 cycles in batch 2 versus 1006 in batch 3), supporting the concept-drift reading of the cross-batch collapse in Section 5.6.", 620, 238).forEach(x => C.push(x));
C.push(table([3360, 2640, 2640], [
  ["Diagnostic (batches 1-2)", "Random forest", "Gaussian process"],
  ["Uncertainty-error Spearman", "0.37 ± 0.14", "0.24 ± 0.13"],
  ["Active learning R² (33-cell budget)", "0.70 ± 0.14", "0.73 ± 0.20"],
  ["Random sampling R² (33-cell budget)", "0.70 ± 0.16", "0.69 ± 0.18"],
]));
C.push(capt("Supplementary Table S4. Diagnosis of the active-learning null result (12 seeds, mean ± s.d., evaluated at a common 33-cell labelling budget). Both surrogate models show only weak correlation between predictive uncertainty and actual error, and neither uncertainty sampler reliably beats random; the better-calibrated Gaussian process does not recover an advantage, pointing to pool homogeneity rather than a model-specific uncertainty defect."));
C.push(H1("Author Contributions, Funding, and Declarations"));
C.push(P("Author Contributions: Conceptualisation, P.W. and Z.Q.; methodology, P.W.; software and formal analysis, P.W. and P.Z.; data curation, P.Z. and S.H.; writing-original draft, P.W.; writing-review and editing, Z.Q., P.Z. and S.H.; supervision, Z.Q. All authors have read and agreed to the published version of the manuscript.", { size: 20 }));
C.push(P("Funding: This research received no external funding.", { size: 20 }));
C.push(P("Institutional Review Board Statement: Not applicable. This study used publicly available electrochemical cycling datasets and did not involve human participants or animals.", { size: 20 }));
C.push(P("Informed Consent Statement: Not applicable.", { size: 20 }));
C.push(P("Data Availability Statement: The datasets analysed in this study are publicly available. The Severson/MATR fast-charging dataset is distributed through the MATR repository, and the NASA PCoE battery ageing dataset through the NASA Open Data Portal. The processed features, data splits and analysis code that reproduce all results are available at [repository URL, e.g. GitHub/Zenodo/OSF] and, in the interim, from the corresponding author upon reasonable request.", { size: 20 }));
C.push(P("Conflicts of Interest: The authors declare no conflict of interest.", { size: 20 }));
C.push(H1("References"));
const refs = [
  "Severson, K. A.; Attia, P. M.; Jin, N.; et al. Data-driven prediction of battery cycle life before capacity degradation. Nature Energy 2019, 4, 383-391. DOI: 10.1038/s41560-019-0356-8.",
  "Li, Y.; Liu, K.; Foley, A. M.; Zülke, A.; Berecibar, M.; Nanini-Maury, E.; et al. Data-driven health estimation and lifetime prediction of lithium-ion batteries: A review. Renewable and Sustainable Energy Reviews 2019, 113, 109254. DOI: 10.1016/j.rser.2019.109254.",
  "Demirci, O.; Taskin, S.; Schaltz, E.; Acar Demirci, B. Review of battery state estimation methods for electric vehicles. Journal of Energy Storage 2024, 87, 111435. DOI: 10.1016/j.est.2024.111435.",
  "Ng, M.-F.; Zhao, J.; Yan, Q.; Conduit, G. J.; Seh, Z. W. Predicting the state of charge and health of batteries using data-driven machine learning. Nature Machine Intelligence 2020, 2, 161-170. DOI: 10.1038/s42256-020-0156-7.",
  "Javaid, M. U.; Seo, J.; Suh, Y.-K.; Kim, S. Y. Battery state of health estimation from discharge voltage segments using an artificial neural network. International Journal of Precision Engineering and Manufacturing-Green Technology 2024, 11, 863-876. DOI: 10.1007/s40684-024-00602-2.",
  "Ren, R.; Linghu, J.; Wang, X.; Dai, J.; Tan, Y.; Chen, C. Mutual information-guided voltage segment selection and lightweight modeling for state of health estimation of batteries with incomplete charging curves. Journal of Power Sources 2026, 687, 240545. DOI: 10.1016/j.jpowsour.2026.240545.",
  "Jelovic, M.; Hochedlinger, S.; Kozek, M.; Jakubek, S.; Hametner, C. Battery state of health estimation for partial charge segments using incremental capacity analysis. Journal of Energy Storage 2026, 171, 122872. DOI: 10.1016/j.est.2026.122872.",
  "Zhang, Y.; Tang, Q.; Zhang, Y.; Wang, J.; Stimming, U.; Lee, A. A. Identifying degradation patterns of lithium-ion batteries from impedance spectroscopy using machine learning. Nature Communications 2020, 11, 1706. DOI: 10.1038/s41467-020-15235-7.",
  "Zhu, J.; Wang, Y.; Huang, Y.; Gopaluni, R. B.; Cao, Y.; Heere, M.; et al. Data-driven capacity estimation of commercial lithium-ion batteries from voltage relaxation. Nature Communications 2022, 13, 2261. DOI: 10.1038/s41467-022-29837-w.",
  "Lin, M.; Wu, D.; Meng, J.; Wu, J.; Wu, H. A multi-feature-based multi-model fusion method for state of health estimation of lithium-ion batteries. Journal of Power Sources 2022, 518, 230774. DOI: 10.1016/j.jpowsour.2021.230774.",
  "Hüllermeier, E.; Waegeman, W. Aleatoric and epistemic uncertainty in machine learning: an introduction to concepts and methods. Machine Learning 2021, 110, 457-506. DOI: 10.1007/s10994-021-05946-3.",
  "Roman, D.; Saxena, S.; Robu, V.; Pecht, M.; Flynn, D. Machine learning pipeline for battery state-of-health estimation. Nature Machine Intelligence 2021, 3, 447-456. DOI: 10.1038/s42256-021-00312-3.",
  "Wu, M.; Yue, C.; Zhang, F.; Sun, R.; Tang, J.; Hu, S.; Zhao, N.; Wang, J. State of health estimation and remaining useful life prediction of lithium-ion batteries by charging feature extraction and ridge regression. Applied Sciences 2024, 14, 3153. DOI: 10.3390/app14083153.",
  "Li, R.; He, N.; Cheng, F. State of health estimation of lithium-ion battery based on novel health indicators and improved support vector regression. Batteries 2025, 11, 347. DOI: 10.3390/batteries11100347.",
  "Dubarry, M.; Svoboda, V.; Hwu, R.; Liaw, B. Y. Incremental capacity analysis and close-to-equilibrium OCV measurements to quantify capacity fade in commercial rechargeable lithium batteries. Electrochemical and Solid-State Letters 2006, 9, A454-A457. DOI: 10.1149/1.2221767.",
  "Weng, C.; Cui, Y.; Sun, J.; Peng, H. On-board state of health monitoring of lithium-ion batteries using incremental capacity analysis with support vector regression. Journal of Power Sources 2013, 235, 36-44. DOI: 10.1016/j.jpowsour.2013.02.012.",
  "Birkl, C. R.; Roberts, M. R.; McTurk, E.; Bruce, P. G.; Howey, D. A. Degradation diagnostics for lithium ion cells. Journal of Power Sources 2017, 341, 373-386. DOI: 10.1016/j.jpowsour.2016.12.011.",
  "Attia, P. M.; Grover, A.; Jin, N.; et al. Closed-loop optimization of fast-charging protocols for batteries with machine learning. Nature 2020, 578, 397-402. DOI: 10.1038/s41586-020-1994-5.",
  "Settles, B. Active Learning Literature Survey; University of Wisconsin-Madison, 2009.",
  "Koza, J. R. Genetic Programming: On the Programming of Computers by Means of Natural Selection; MIT Press: Cambridge, MA, 1992.",
  "Schmidt, M.; Lipson, H. Distilling free-form natural laws from experimental data. Science 2009, 324, 81-85. DOI: 10.1126/science.1165893.",
  "Brunton, S. L.; Proctor, J. L.; Kutz, J. N. Discovering governing equations from data by sparse identification of nonlinear dynamical systems. Proceedings of the National Academy of Sciences 2016, 113, 3932-3937. DOI: 10.1073/pnas.1517384113.",
  "Vovk, V.; Gammerman, A.; Shafer, G. Algorithmic Learning in a Random World; Springer, 2005.",
  "Angelopoulos, A. N.; Bates, S. A gentle introduction to conformal prediction and distribution-free uncertainty quantification. arXiv:2107.07511, 2021.",
  "Saha, B.; Goebel, K. Battery Data Set (B0005, B0006, B0007, B0018). NASA Ames Prognostics Data Repository; NASA Ames Research Center: Moffett Field, CA, 2007. Available via the NASA Open Data Portal, https://data.nasa.gov/dataset/li-ion-battery-aging-datasets (accessed 2025).",
  "He, W.; Williard, N.; Osterman, M.; Pecht, M. Prognostics of lithium-ion batteries based on Dempster-Shafer theory and the Bayesian Monte Carlo method. Journal of Power Sources 2011, 196, 10314-10321. DOI: 10.1016/j.jpowsour.2011.08.040.",
  "Savitzky, A.; Golay, M. J. E. Smoothing and differentiation of data by simplified least squares procedures. Analytical Chemistry 1964, 36, 1627-1639. DOI: 10.1021/ac60214a047.",
  "Pedregosa, F.; et al. Scikit-learn: Machine learning in Python. JMLR 2011, 12, 2825-2830.",
  "Smola, A. J.; Schölkopf, B. A tutorial on support vector regression. Statistics and Computing 2004, 14, 199-222. DOI: 10.1023/B:STCO.0000035301.49549.88.",
  "Breiman, L. Random forests. Machine Learning 2001, 45, 5-32. DOI: 10.1023/A:1010933404324.",
  "Stephens, T. gplearn: Genetic Programming in Python (software), 2016. https://github.com/trevorstephens/gplearn.",
  "Zhang, Y.; Xiong, R.; He, H.; Pecht, M. G. Long short-term memory recurrent neural network for remaining useful life prediction of lithium-ion batteries. IEEE Transactions on Vehicular Technology 2018, 67, 5695-5705. DOI: 10.1109/TVT.2018.2805189.",
  "Chen, L.; Xie, S.; Lopes, A. M.; Bao, X. A vision transformer-based deep neural network for state of health estimation of lithium-ion batteries. International Journal of Electrical Power & Energy Systems 2023, 152, 109233. DOI: 10.1016/j.ijepes.2023.109233.",
  "Gibbs, I.; Candès, E. J. Adaptive conformal inference under distribution shift. Advances in Neural Information Processing Systems (NeurIPS) 2021, 34, 1660-1672.",
  "Edge, J. S.; O'Kane, S.; Prosser, R.; et al. Lithium-ion battery degradation: what you need to know. Physical Chemistry Chemical Physics 2021, 23, 8200-8221. DOI: 10.1039/d1cp00359c.",
  "Dubarry, M.; Truchot, C.; Liaw, B. Y. Synthesize battery degradation modes via a diagnostic and prognostic model. Journal of Power Sources 2012, 219, 204-216. DOI: 10.1016/j.jpowsour.2012.07.016.",
  "Rasmussen, C. E.; Williams, C. K. I. Gaussian Processes for Machine Learning; MIT Press: Cambridge, MA, 2006. DOI: 10.7551/mitpress/3206.001.0001.",
  "Gretton, A.; Borgwardt, K. M.; Rasch, M. J.; Schölkopf, B.; Smola, A. A kernel two-sample test. Journal of Machine Learning Research 2012, 13, 723-773.",
  "Tan, Y.; Zhao, G. Transfer learning with long short-term memory network for state-of-health prediction of lithium-ion batteries. IEEE Transactions on Industrial Electronics 2020, 67, 8723-8731. DOI: 10.1109/TIE.2019.2946551.",
  "Tibshirani, R. J.; Foygel Barber, R.; Candès, E. J.; Ramdas, A. Conformal prediction under covariate shift. Advances in Neural Information Processing Systems (NeurIPS) 2019, 32. arXiv:1904.06019.",
  "Romano, Y.; Patterson, E.; Candès, E. J. Conformalized quantile regression. Advances in Neural Information Processing Systems (NeurIPS) 2019, 32, 3543-3553. arXiv:1905.03222.",
  "Barber, R. F.; Candès, E. J.; Ramdas, A.; Tibshirani, R. J. Conformal prediction beyond exchangeability. The Annals of Statistics 2023, 51 (2), 816-845. DOI: 10.1214/23-aos2276.",
]
refs.forEach(r => C.push(new Paragraph({ numbering: { reference: "refs", level: 0 },
  spacing: { after: 80 }, children: [new TextRun({ text: r, size: 20 })] })));

// ---------- document ----------
const doc = new Document({
  styles: {
    default: { document: { run: { font: "Arial", size: 22 } } },
    paragraphStyles: [
      { id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 26, bold: true, font: "Arial" }, paragraph: { spacing: { before: 240, after: 120 }, outlineLevel: 0 } },
      { id: "Heading2", name: "Heading 2", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 23, bold: true, font: "Arial" }, paragraph: { spacing: { before: 160, after: 100 }, outlineLevel: 1 } },
    ],
  },
  numbering: { config: [
    { reference: "b", levels: [{ level: 0, format: LevelFormat.BULLET, text: "•", alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 540, hanging: 270 } } } }] },
    { reference: "refs", levels: [{ level: 0, format: LevelFormat.DECIMAL, text: "%1.", alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 480, hanging: 300 } } } }] },
  ] },
  sections: [{
    properties: { page: { size: { width: 12240, height: 15840 }, margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } } },
    footers: { default: new Footer({ children: [new Paragraph({ alignment: AlignmentType.CENTER,
      children: [new TextRun({ size: 18, children: ["Page ", PageNumber.CURRENT] })] })] }) },
    children: C,
  }],
});

const OUT = process.env.OUT || "manuscript.docx";
Packer.toBuffer(doc).then(buf => { fs.writeFileSync(OUT, buf); console.log(OUT, "written,", buf.length, "bytes"); });
